version: '3'

services:
    frontend:
        build:
            context: .
            dockerfile: ./deploy/development/Dockerfile-frontend
        volumes:
            - ./frontend:/home/dbfinal/workdir/frontend:ro
            - ./database:/home/dbfinal/workdir/database
        ports:
            - '8000'
    backend:
        build:
            context: .
            dockerfile: ./deploy/development/Dockerfile-backend
        volumes:
            - ./backend:/home/dbfinal/workdir/backend:ro
            - ./database:/home/dbfinal/workdir/database
        ports:
            - '8001'
    nginx:
        image: nginx:stable
        volumes:
            - ./deploy/development/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx-logs:/etc/nginx/logs
        ports:
            - '80:80'
        expose:
            - '80'
