version: '3'

services:
    frontend:
        build: frontend
        restart: on-failure
        expose:
            - '8000'

    backend:
        build: backend
        restart: on-failure
        depends_on:
            - mariadb
        env_file:
            - mariadb.env
        expose:
            - '8001'

    mariadb:
        image: mariadb:focal
        restart: on-failure
        volumes:
            - ./database/mariadb-init:/docker-entrypoint-initdb.d:ro
            - ./database/csv:/var/lib/mysql/csv
            - ./logs/mariadb:/var/lib/mysql/logs
            - ./mariadb.conf:/etc/my.cnf:ro
        env_file:
            - mariadb.env
        expose:
            - '3306'

    nginx:
        image: nginx:stable
        restart: on-failure
        depends_on:
            - frontend
            - backend
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./logs/nginx:/etc/nginx/logs
        ports:
            - '80:80'
