version: '3'

services:
    web:
        build: .
        volumes:
            - .:/home/dbfinal/workdir:ro
            - ./database:/home/dbfinal/workdir/database
        ports:
            - '8000:8000'
        expose:
            - '8000'
