version: '3'

services:
    frontend:
        build:
            context: .
            dockerfile: ./deploy/production/Dockerfile-frontend
        volumes:
            - ./frontend:/home/dbfinal/workdir/frontend:ro
            - ./database:/home/dbfinal/workdir/database
            - ./uwsgi-logs:/var/log/uwsgi/
        ports:
            - '8000'
    backend:
        build:
            context: .
            dockerfile: ./deploy/production/Dockerfile-backend
        volumes:
            - ./backend:/home/dbfinal/workdir/backend:ro
            - ./database:/home/dbfinal/workdir/database
            - ./uwsgi-logs:/var/log/uwsgi/
        ports:
            - '8001'
    nginx:
        image: nginx:stable
        volumes:
            - ./deploy/production/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx-logs:/etc/nginx/logs
        ports:
            - '80:80'
        expose:
            - '80'
