FROM alpine:3.13

USER root

RUN apk update
RUN apk add python3 py3-pip uwsgi-python3

RUN adduser -h /home/dbfinal -D dbfinal
RUN chown -R dbfinal:dbfinal /home/dbfinal
RUN chmod -R 755 /home/dbfinal
USER dbfinal:dbfinal

WORKDIR /home/dbfinal/workdir
COPY backend/requirements.txt .
RUN pip install -r requirements.txt

COPY deploy/production/uwsgi-backend.ini uwsgi.ini
CMD ["uwsgi", "--ini", "uwsgi.ini"]
